### PR TITLE
Variation ch8 ch9

### PR DESCRIPTION
**Pull request by OliviaFS**
## Description

Variation collation by Olivia

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How has this been tested?
Manually

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

## Checklist:

- [x ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## What should reviewers look for?

Please provide any specific areas of feedback you're looking for from reviewers.

### CODE REVIEW

**Review by tiagosousagarcia — CHANGES_REQUESTED** [review]
- The `app` that starts on line 9521 (`<app type="major" subtype="add"><lem wit="#b1623">some swarmes are sufficiently provided: which you may reckon as Jewels`) seems to go on for quite a few pages, if I understood it correctly; if that's the case, because it starts in the middle of a page, you will need to split this `app` into several `app`s, one per page

Won't have the time to look at anything else today, so just this for now

**Review by tiagosousagarcia — DISMISSED** [review]
All good, free to merge

**Comment by OliviaFS** [comment]
Hello @tiagosousagarcia, I have fixed this hopefully.

**Review by tiagosousagarcia — CHANGES_REQUESTED** [review]
@OliviaFS -- at some point, when we were merging, we brought the changes to other chapters as well, and a couple of new errors popped up: anchors with ids 'ch6ancs6' and 'ch6ancs49' are missing from '1609.xml' -- could you verify where they are and add them? also remember to pull the changes to this branch, I've made a couple of corrections

**Comment by OliviaFS** [comment]
Do you mean in the variation 8-9 branch? Because I can see ch6ancs6 in there

**Comment by tiagosousagarcia** [comment]
You might have it on your local machine, but it is definitely not in github -- https://github.com/NewcastleRSE/beeing-human-tei-data/blob/Variation-ch8-ch9/1609.xml -- make sure you have the correct 1609 file opened, and if you do save and commit

**Review by tiagosousagarcia — CHANGES_REQUESTED** [review]
Sorry, we're still missing `ch6ancs49` in 1609.xml

**Review by tiagosousagarcia — APPROVED** [review]
All good now, thanks! Merge away

**Pull request merged**
