### PR TITLE
Starting quote-notes branch

### LINKED ISSUE #17: Ensure <note> associated with <quote> element appear inside the <quote>
### Summary

*Wherever possible, a `<quote>` element should contain its associated `<note subtype='bibliographic'>`. This was not consistently done, so the cases where this does not happen currently appear as warnings. Correct this and take note of any place where the bibliographic note does not exist.*

For example:
```
<quote>
    <foreign xml:lang="la">Fructus apum ab omnibus desideratur, &amp; quæritur:
                            nec pro personarum diversitate discernitur, sed indiscreta sui gratia
                            regibus pariter ac mediocribus æquali suavitate dulcescit: nec solùm
                            voluptati, sed etiam saluti est.</foreign>
</quote>
<note type="authorial" subtype="bibliographic" xml:id="ch1bibln1">Ambrosius
                        Hexamer. l.5.cap.21.</note>
```
should become
```
<quote>
    <foreign xml:lang="la">Fructus apum ab omnibus desideratur, &amp; quæritur:
                            nec pro personarum diversitate discernitur, sed indiscreta sui gratia
                            regibus pariter ac mediocribus æquali suavitate dulcescit: nec solùm
                            voluptati, sed etiam saluti est.</foreign>
    <note type="authorial" subtype="bibliographic" xml:id="ch1bibln1">Ambrosius
                        Hexamer. l.5.cap.21.</note>
</quote>
```

### What needs to be done?

- [ ] *Correct all cases with warnings*
- [ ] *Make a note of any cases without a bibliographic note*

### Who can help?

- @tiagosousagarcia

### PR DESCRIPTION
**Pull request by OliviaFS**
## Description

So far I've got a problem at 1714 -- this is a quote from Virgil and I will need to create a separate note for the internal Butler ref. But the main problem is that something is stopping me surrounding the whole thing with quote...I think it is the <p> 

I am not confident to move it all around, but I can 

Fixes #17 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How has this been tested?

Manually

## Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by tiagosousagarcia — COMMENTED** [review]
@OliviaFS We've discussed this via slack, but just leaving it here for reference: when there are interjections, envelope everything in a quote, and add an editorial note to check the interjection later, like so:
```
<persName rend="italic"> Plinie</persName> reporteth, they were pleased to spend most of their time in this pleasing
                    businesse. <quote>
                        <foreign xml:lang="la">Ne quis</foreign>
                     (saith hee)<note xml:id="prefaceX1" type="editorial" subtype="other" cert="check" ana="interjection"/>
                        <foreign xml:lang="la">miretur amore carum captos Aristomachum Solensem
                            duodesexaginta annis nihil aliud egisse; Philiscum vero Thasium in
                            desertis apes colentem <hi rend="opposite">Agrium</hi> cognomimatum: qui
                            ambo scripsere de his</foreign>
                        <note
                        type="authorial" subtype="bibliographic" xml:id="frontbibln3">
                        <bibl rend="italic">Nat hist.l.II.c.9.</bibl>
                    </note>
                     .</quote>
```

A couple of things to note from this example:
-- here I think the quote only really starts with  the Latin, so you can leave what Butler 'reporteth' out of the tag -- I think it's more a paraphrase of what follows, than additional information.
-- You can move the bibliographic note to inside the quote itself (in fact, that's what should happen), where we put the notes on the text was mostly for convenience, the important thing is that the bibliographic note is connected to that quote. Unless they appear very far away from their quote, I would always move the bibliographic note to inside the quote.
-- Don't forget to add the editorial note next to the interjection: for every case like this, the note can be exactly the same as the one I have in the example, except for the xml:id which needs to be unique. Just create one based on the usual conventions part of text - type of note - numeral. If the id for the note already exists, Oxygen will not validate, and you'll see an error saying the code must be unique.

Let me know if you have any questions

**Review by tiagosousagarcia — CHANGES_REQUESTED** [review]
Looks good, corrected only a few things, and resolved the merge conflicts. Pull the changes to the branch before making any more edits. You might get conflicts when you do this -- if that happens, delete your local copy of the branch, and checkout the remote again. If you run into trouble doing that, let me know and we'll have a quick call where I'll guide you through the process. Re-request the review once you finish everything.

**Comment by OliviaFS** [comment]
@tiagosousagarcia Here are the last bits to check. All these were difficult in some way so I apologise in advance for mistakes. Now I will get on with the comparison.

**Comment by tiagosousagarcia** [comment]
Thanks @OliviaFS -- I'm tied up with something else for the rest of the day, but I'll check it first thing tomorrow morning

**Comment by OliviaFS** [comment]
Thanks,  no hurry (I assume it is fine to do the comparison without merging this).

**Comment by tiagosousagarcia** [comment]
yes, should not be a problem -- might need to do some merging conflict solving down the line, but if you do the comparison in small chunks it should be manageable.

**Review by tiagosousagarcia — APPROVED** [review]
All looks good, great work! Don't worry about merging this, I'll do it since I'm already here.

**Pull request merged**
