### PR TITLE
Change refs

### LINKED ISSUE #15: Add targets to cross-reference <ref>
### Summary

Internal cross-references are encoded using a `<ref>` element with a `@target` attribute. Most of these are currently empty (or rather, containing a simple `#`). Add the correct `xml:id` to each of these references. You can deduce the correct `xml:id` from the content of the `<ref>` itself. The `xml:id` always follows the same pattern: chXAAAnY where `X` is the number of the chapter, `AAA` is a code for the type of note -- `sum` for summary notes, `bibl` for bibliographic notes, `glo` for gloss notes - and Y is the number of the specific note. So, a note like:
```
<ref target="#">V.c.6.n.41.</ref>
```
should become 
```
<ref target="#ch6sumn41">V.c.6.n.41.</ref>
```

The only exceptions are for chapter 10, which also include a part information immediately after the chapter number, so:
```
<ref target="#">V.c.10.p.1.n.3.</ref>
```
should become
```
<ref target="#ch10p1sumn3">V.c.10.p.1.n.3.</ref>
```
### What needs to be done?

- [ ] *Add the xml:id of the target for all \<ref\>*
- [ ] *Make sure they all link correctly*

### Who can help?

- @tiagosousagarcia

---

### PR DESCRIPTION
**Pull request by OliviaFS**
## Description

I have just done more ref and id updates, and am using this as a way of saving them. I worry a little that the same ones are coming back/not saving/dev didn't update in time for the amendments to show in my new branch? But it's probably just that there are lots of them!

Fixes #15 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How has this been tested? 
Manual test

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

## Checklist:

- [ x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## What should reviewers look for?

As above

### CODE REVIEW

**Review by tiagosousagarcia — COMMENTED** [review]
@OliviaFS, tagging you to make sure you're getting notified of this.

There were some weird conflicts between what's on the dev branch and this branch -- not sure how this happened, you might have started a new branch before updating dev or it might be some other weirdness. In any case, it doesn't matter: I've resolved these merge conflicts, so make sure you **pull** the new changes to this branch before adding more stuff, saving and committing.

Your changes are definitely saving though, there are only 179 more cases of this (compared to 361 on dev), so keep going! It can be a bit dull and repetitive, so that might explain it somewhat. As you go along, keep an eye out on the number of outstanding infos (very bottom of the screen, should be a status bar with 'Validation successful. Warnings: 167. Info: xxx'. The number of infos should decrease as you go along. If it isn't, validate the document every so often (the button with a blank document and a checkmark, or cmd+shift+v, or Document>Validate>Validate

**Comment by OliviaFS** [comment]
line 6603 where the superscript 'a' is needs to be classed as a glossary note, but I can't work out how to add it as one without disrupting the sequence of numbered notes. Could you help, thanks @tiagosousagarcia

**Comment by tiagosousagarcia** [comment]
> line 6603 where the superscript 'a' is needs to be classed as a glossary note, but I can't work out how to add it as one without disrupting the sequence of numbered notes. Could you help, thanks @tiagosousagarcia 

Ah, yes, well spotted @OliviaFS -- there's a way, but I'll look at it more carefully tomorrow and either fix it myself or tell you how to fix it. Just ignore it for now and keep going. And commit often, every few changes or so.

**Comment by tiagosousagarcia** [comment]
> > line 6603 where the superscript 'a' is needs to be classed as a glossary note, but I can't work out how to add it as one without disrupting the sequence of numbered notes. Could you help, thanks @tiagosousagarcia
> 
> Ah, yes, well spotted @OliviaFS -- there's a way, but I'll look at it more carefully tomorrow and either fix it myself or tell you how to fix it. Just ignore it for now and keep going. And commit often, every few changes or so.

Ok, just had a look this morning and actually no action is needed @OliviaFS -- The note actually starts a couple of lines before (6599), but then contains the two side-notes before the superscript 'a'. The entire content of the note is as follows (6599 to 6618):

```
                <note type="authorial" subtype="gloss" place="inline" xml:id="ch6glon4"><note
                        type="authorial" subtype="bibliographic" xml:id="ch6bibln48">
                        <bibl>Virg.Geor.</bibl>
                    </note><note type="authorial" subtype="summary" xml:id="ch6sumn55">55. How to
                        finde wilde Bees.</note>
                    <hi rend="superscript">a</hi> For they will never goe farre for water, if any be
                    to be had neere hand. <quote>
                        <foreign xml:lang="la">Sub mænibus urbis aquantur.</foreign>
                    </quote> And therefore when you see Bees watring in woods or other places, not
                    neere any Hives; bee sure those are wilde Bees, which are not farre from their
                    neast. Watch them therefore which way they flie: for they will thence directly
                    to it. Which if it be not within view, take a Reede or Kex, or some like hollow
                    thing open at one end, with a chinke cut in the other to let in light: and
                    taking up a Bee by the wings put her into the Cane, and shut her in with your
                    thumb: while she goeth downe to the light, put in an other, and so many as you
                    thinke good. And then where you last see the Bees flying homeward from the
                    water, goe to that place, and there let out one of the Bees in the box: which,
                    when she hath cast a Ring to know where she is, will fly as directly home as the
                    other: likewise where you see her last, let out another: and so the rest, untill
                    they have brought you to the stall.</note>
```

**Pull request merged**
