### PR TITLE
Corr 1609 jr

### PR DESCRIPTION
**Pull request by jr970**
## Description

I have made a large number of minor corrections to the 1609 transcription in this branch. I made my corrections in batches, saved and pushed, 

## How has this been tested?

I checked corrections as I was entering them; the whole transcript will be checked again at a later date. There is one more complicated change that I need to make but I don't know how it should be coded. No red warnings appeared.

## Checklist:

- [ ] I have performed a self-review
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

### CODE REVIEW

**Comment by jr970** [comment]
I will need help resolving some of the conflicts.

**Comment by jr970** [comment]
I will need help resolving some of the conflicts,

**Comment by tiagosousagarcia** [comment]
@jr970 the conflicts are the ones I was expecting -- which is a good thing. I can solve them easily but I need some the time to concentrate, which I can't right now with a hyperactive toddler jumping about -- I'll solve this first thing tomorrow morning

**Comment by jr970** [comment]
Excellent - and when you have a quiet moment of course! J

Jennifer Richards, FBA, FEA
https://www.english.cam.ac.uk/people/Jennifer.Richards
Chair of The English Association
English (2001) Professor, University of Cambridge
Fellow of Peterhouse
Visiting Professor, Newcastle University

Personal zoom:
https://cam-ac-uk.zoom.us/j/7385624872?pwd=VEtWTjNrYnZRUkh0MUpGYzQ0TVdnZz09



________________________________

**Review by tiagosousagarcia — APPROVED** [review]
Corrected the merge problems, good to go now

**Pull request merged**
