### PR TITLE
Variation chapter1

### PR DESCRIPTION
**Pull request by OliviaFS**
## Description

Comparing 1609 and 1623

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How has this been tested?

Manually

## Checklist:

- [ x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## What should reviewers look for?

Helping to troubleshoot

### CODE REVIEW

**Comment by OliviaFS** [comment]
Problems at l1839 - I think it is too large a chunk for me to encapsulate
in <app>

**Review by tiagosousagarcia — CHANGES_REQUESTED** [review]
Everything looks fine at a quick review -- in 1609.xml, ll.1415-1416, the anchors should be inside the `<head>` tags.

there are two problems at around l.1828:
-- You are self-closing the first `app`: remove the `/` at the end of the starting `app` tag
-- in the next app, the problem is conflicting hierarchies, you need to divide it into two `<app>`. Everything that opens inside an element must also close inside the same element: in that one, the first paragraph was open outside the `<app>`, so it must close outside of it as well. To divide, you need to close the `<app>` before the end of that first paragraph:
```
...Which done, the strife presently ended, and the Bees
                    agreed well together.</lem></app> </p>
```
The start of that `<app>` also needs to take in the entirety of the note, otherwise you have the same problem, so it should be:
```
<app type="substantive" subtype="add"><lem wit="#b1623"><note type="authorial" subtype="summary" xml:id="ch1sumn8">8. A memorable
                        experiment.</note> Two swarmes...
```
After that, you immediately open another `<app>` that will take the entirety of `<p xml:id="ch1par8">` and end where it currently ends. 

So, instead of one big `<app>` that starts in the middle of a paragraph and ends in another, you will have to divide that into two `<app>`, one for each paragraph. This doesn't mean that all changes that are longer than a paragraph need to be that way, only the ones that start or end in the middle of one. If the change is the addition of one (or two, or three, or however many) entire paragraphs, all of that can be a single change (unless it crosses other larger structures, like a div).

Let me know if this makes sense, if not we can have a quick call and I'll guide you through the process.

**Comment by OliviaFS** [comment]
Hello, that really does make sense, thanks. I was worried it would matter that it seemed like two changes but I see it doesn't really matter. 
Thanks

**Comment by OliviaFS** [comment]
Everything looks fine at a quick review -- in 1609.xml, ll.1415-1416, the anchors should be inside the <head> tags.

^^Especially sorry about this, which you had just told me before!!

**Comment by tiagosousagarcia** [comment]
Yeah, it doesn't matter unless you are counting how many individual changes exist (but then you have to problematically define what constitutes a single change) -- it's not ideal, but this scenario is, unfortunately, one of the drawbacks of the TEI (conflicting hierarchies happen, and is the number 1 complaint of people encoding text). There are ways around it if later we find we really want to make sure those two `<app>` are in fact a single one, but I would not want to go down that road unless it is relevant. For the end user, the result is pretty similar.

**Comment by OliviaFS** [comment]
Would it be possible to have an 'app' category for adding new references. Called 'reference' or something?

**Comment by tiagosousagarcia** [comment]
> Would it be possible to have an 'app' category for adding new references. Called 'reference' or something?

We can, though we might need to discuss whether we need it or not -- can you open an issue about this, so that we can track the discussion there ([how to use issues](https://github.com/NewcastleRSE/beeing-human-tei-data/blob/test-display-variation/documentation/guides/31_Github_issues/31_github_issues.md))? Include an example, and maybe propose how you'd like to see the resulting change.

(we don't strictly need an issue here, but it's good practice for when we find more challenging problems later on)

**Review by tiagosousagarcia — DISMISSED** [review]
All seems good

**Review by tiagosousagarcia — COMMENTED** [review]
Can you review the positions of the following anchors in 1609:
- `ch1ancs9` and `ch1ance9`
- `ch1ancs12` and `ch1ance12`
- `ch1ancs14` and `ch1ance14`
- `ch1ancs18` and `ch1ance18`

Make sure they are where they should be, that they are not cutting across any other markup, and that they cannot be divided into smaller ones.

If they are correct that's fine, just let me know, I'll need to make some changes to one of my scripts

**Comment by OliviaFS** [comment]
Hi, so
ch1ancs9 and ch1ance9
-This is a funny note that starts in the margin but ends up in the main page, pic attached. It is correct but it is weird. 
Screenshot 2023-11-03 at 11 48 15

ch1ancs12 and ch1ance12
- this variation starts after the first few words of the paragraph and I thought it interesting enough to be granular, but doesn't have to be. 

ch1ancs14 and ch1ance14
-See how I've tried to fix it! May not be appropriate. 

-ch1ancs18 and ch1ance18
Should this be inside the <note> tag?

**Comment by OliviaFS** [comment]
It's good to use these as examples for me to learn what we'll standardly do

**Comment by OliviaFS** [comment]
Also should I be updating the changes list at the start of the file with this process? On both files? I think I might have forgotten about that, sorry.

**Comment by tiagosousagarcia** [comment]
So, I've made a couple of smaller changes, but I still need your help with the 12s and 14s -- see below. By the way, none of this was your mistake, it is perfectly valid -- I'm just trying the find the optimal way to transform this.

-- #ch1ancs9 #ch1ance9 -- moved the anchors to inside the `<note>`
-- #ch1ancs12 #ch1ance12 -- can you break that app into two? One for the body of the text, the other for the side note?
-- #ch1ancs14(sx) -- yeah, I think I get what you did, but you forgot to add another app in 1623: so you need to have one app for the 14 set of anchors, and another app for the 14x set of anchors
-- #ch1ancs18 #ch1ance18 -- yeah, anchors inside the note



> Also should I be updating the changes list at the start of the file with this process? On both files? I think I might have forgotten about that, sorry.

I wouldn't bother with every single change -- as long as you remember to update once for each pull request that's fine.

**Comment by tiagosousagarcia** [comment]
Right, I think I corrected the problems I had on the script on my side -- make sure to pull any changes. We should aim to merge this branch tomorrow, so that Jenny can use the Wed afternoon to read through things on her side; we can then open another branch for the remainder of chapter 1

**Comment by OliviaFS** [comment]
I'll have another look through but I think it's more or less ready at this stage

**Review by tiagosousagarcia — APPROVED** [review]
All looks good, merging now

**Pull request merged**
