### PR TITLE
Adding bits of @rend to 'hi' (mainly rend="italic")

### PR DESCRIPTION
**Pull request by OliviaFS**
## Description

Adding @rend elements to 'hi' tags

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How has this been tested?

Manually

## Checklist:

- [x ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## What should reviewers look for?

@tiagosousagarcia to check periodically

### CODE REVIEW

**Review by tiagosousagarcia — CHANGES_REQUESTED** [review]
@OliviaFS, can you check what's going on with lines 9609-9612? Why do we have single letter foreign words?

**Comment by OliviaFS** [comment]
Yes, that's ok, he's talking about how to say Metheglen and about German 'd' sounds and English 'th' sounds -- basically etymology of how it relates to 'mede' or 'mead'

**Comment by OliviaFS** [comment]
Actually the sort of passage that Jenny would find v interesting for her research

**Review by tiagosousagarcia — APPROVED** [review]

**Comment by tiagosousagarcia** [comment]
Cool thanks! Let's go ahead and merge then

**Pull request merged**
