### PR TITLE
Variation ch6

### PR DESCRIPTION
**Pull request by OliviaFS**
## Description

Variation collation by Olivia

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How has this been tested?
Manually

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

## Checklist:

- [ x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## What should reviewers look for?

Please provide any specific areas of feedback you're looking for from reviewers.

### CODE REVIEW

**Review by tiagosousagarcia — APPROVED** [review]
I think all is good now, so feel free to pass this one on to Jenny -- though maybe give it a quick once over, I've reviewed this in 2 minute chunks in between a day absolutely full of meetings, so I might have left a few things pass. I'll try to review the remaining PRs by tomorrow

**Comment by OliviaFS** [comment]
Thanks, I don't need to merge now do I?

**Comment by tiagosousagarcia** [comment]
Yeah you do for Jenny to be able to see it

**Comment by OliviaFS** [comment]
Ok I've merged 6 and will resolve the conflicts in the others and send them
back through the system

**Comment by tiagosousagarcia** [comment]
Don't do anything to the ch-7 branch yet, I'm still looking through it!

**Pull request merged**
